AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
